name: senai_automacao
run-name: ${{ github.actor }} Pipeline deploy
on:
  push:
    branches:
      - "main"
    paths:
      - 'images/**' # Considerando que as imagens estão no diretório 'images/'
      - '!*.txt'    # Ignora os arquivos .txtss

jobs:
  githubactions-senai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Transfer images to server
        run: |
          scp -r images/* ec2-use@54.211.167.113:/home/ec2-user/imagem

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
